name: UnitTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Print Python package versions
        run: |
          pytest --version
          coveralls --version

      # Test with PyTorch 1.3.1
      - name: Install PyTorch 1.3.1
        run: pip install torch == 1.3.1

      - name: Test with PyTorch 1.3.1
        run: |
          export TENSORKIT_BACKEND=PyTorch TENSORKIT_JIT_MODE=none
          pytest --cov=tensorkit --cov-append

      - name: Test with PyTorch 1.3.1, with validate_tensors=True
        run: |
          export TENSORKIT_BACKEND=PyTorch TENSORKIT_VALIDATE_TENSORS=true TENSORKIT_JIT_MODE=none
          pytest --cov=tensorkit --cov-append

      - name: Test with PyTorch 1.3.1, with jit_mode=all
        run: |
          export TENSORKIT_BACKEND=PyTorch TENSORKIT_JIT_MODE=all
          pytest --cov=tensorkit --cov-append

      - name: Submit result to coveralls.io
        run: coveralls
        env:
          COVERALLS_SERVICE_NAME: github
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_GIT_BRANCH: ${{ github.ref }}
          COVERALLS_GIT_COMMIT: ${{ github.sha }}
