name: unittest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Run the test via docker
        run: |
          sudo docker run -t --rm \
            -v "$(pwd)":/prj \
            --build-arg CACHEBURST="$(date +%s)" \
            --env COVERALLS_SERVICE_NAME=github \
            --env COVERALLS_REPO_TOKEN="${{ secrets.GITHUB_TOKEN }}"
            --env COVERALLS_GIT_BRANCH="${{ github.ref }}"
            --env COVERALLS_GIT_COMMIT="${{ github.sha }}"
            "haowenxu/ml-runtime2:cpu-py${{ matrix.python-version }}"
            bash /prj/.github/workflows/unittest.sh
