name: unittest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Generate docker file
        run: |
          cat ./.github/workflows/Dockerfile >> Dockerfile
          sed -i 's/py3.6/py${{ matrix.python-version }}/g' Dockerfile
          cat Dockerfile

      - name: Run the test via docker
        run: |
          sudo docker build -t tensorkit-pytest .
          sudo docker run -t --rm \
            -v "$(pwd)":/prj \
            --build-arg CACHEBURST="$(date +%s)" \
            --env COVERALLS_SERVICE_NAME=github \
            --env COVERALLS_REPO_TOKEN="${{ secrets.GITHUB_TOKEN }}"
            --env COVERALLS_GIT_BRANCH="${{ github.ref }}"
            --env COVERALLS_GIT_COMMIT="${{ github.sha }}"
            tensorkit-pytest
